fix: Remove global react-scripts from client container
- Travis CI keeps failing even after reverting changes that could
  have caused issues
- Error:
    Cannot find module 'enzyme' from 'setupTests.js'
      at Resolver.resolveModule (../../local/lib/node_modules/react-scripts/node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (src/setupTests.js:1:844)